- id: doi:10.1186/s13059-022-02677-z
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1186%2Fs13059-022-02677-z/MediaObjects/13059_2022_2677_Fig1_HTML.png
  date: '2022-5-11'
  publisher: Genome Biology
  extra-links:
    - type: manubot
      link: https://github.com/masoodlab/CRC-Single-Cell  

- id: doi:10.1186/s12943-018-0923-9
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1186%2Fs12943-018-0923-9/MediaObjects/12943_2018_923_Fig1_HTML.png
  date: '2018-11-21'
  publisher: Molecular Cancer